language: node_js
node_js:
  - lts/*

deploy:
  provider: heroku
  api_key:
    secure: EYviBbwdms7Imd44QHBea3O+jcfRmfn6m+Yv/GcCAKKNnsN3ZmmIVn6C6GCveTtooauDSqYMTVBNQ5Jj1WfMJTIkesa7V6SA/BgzhVgbEW+UNaXwhPoFJYE+a2zv+Ogzftwgi1+d7Z/fbqCcX/FcI9ojrwqO72XEFJ9JnUtmjyrA28zmf3XJGZtfM6kQArl/Y332dS6kfbpO/Ag5bOH5Z5lkI/HgViUZbt1DcKVFymp23lpyXZ1unQIuiWhjq+XOnt1I2eHBnN6Xpm7AjKgiC1A+QZulIrmnOLLfagDHaY6pTcfsKtBVhvvoVmI54I47QvWRnOQ5TCL5yoS0EK5BuQXMjVVAYrs/LF8ot+/1xSkYR7Bhl43LK+efDU1vVprygFXVS5dAlSKkg0gE3BFMOJB3/pswefMUdSVINBr6JoablGHPmLvU74FWiOLsXbHzshJf0ods5ollFWKq2OXU2zOINZVsnFoP3iCxTDXaQIGoIlD22tU/9A0ARKBGICimviSdWv+sCCErYXvkAfEAYURQZhqXpyqkV29B2TGrZzIPiTVjzFLPC9Nzvw+Vx4iYbj1oyVhO2pUjXSezaOFy3tOb7P0TvjDusHAi4wAKQcKf/tn+LYYxxNQrBXstW+7qZRQN5HGEWEalfnD6myAdGP0GBPTYMO4t/Ppm9VJ6pSo=
